version: '3.8'

services:
  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "30002:3000"
    environment:
      NODE_ENV: development
    restart: unless-stopped

  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "80002:8000"
    restart: unless-stopped