version: '3.8'

services:
  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "30001:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped

  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "80001:8000"
    env_file:
      - ./be/.env
    environment:
      QDRANT_HOST: 160.191.88.194
      QDRANT_PORT: 6333
    restart: unless-stopped